apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: drdinaokasha/k8s-max-users:latest
          env:
            - name: AUTH_ADDRESS
              value: "auth-service.default"        #it is service name + . + the namespace name



            # - name: AUTH_ADDRESS                 /in case using clusterIP for pod-pod connection
              # value: "10.97.222.169" 

            # OR 
        
              # value: localhost                   /in case communication between containers inside the same pod
           
         